### ISSUE TITLE
License questions

### ISSUE THREAD

**Issue by aptitude** [fwalch/tum-thesis-latex#4]
Is it with the "Creative Commons Attribution-ShareAlike 4.0 International License." intended, that the complete thesis must be published under these conditions?

Or should someone who e.g. add design improvements just create a pull request?

**Comment by fwalch** [comment]
Sorry, I don't know how I keep missing that someone created an issue here, I thought I should get an email or at least a GitHub notification. I'm watching the repo, after all..

Anyway.. the intention behind the license was that the template is to be distributed under these terms, not the complete thesis. If you have suggestions for improvements, by all means, create a pull request. I guess I'll simply adapt the readme to indicate that I'm not the sole author, so all contributors are credited.

I mainly used Creative Commons because the templates at latextemplates.com were using it, but maybe it's not appropriate. I'll think about what to do.

**Comment by fwalch** [comment]
Does https://github.com/fwalch/tum-thesis-latex/commit/b41f32b8bf776dad9a5fdc4c745a34ed0f91c93c answer your questions?

**Comment by aptitude** [comment]
Thank you very much! Yes, this answered my questions.

(And thank you for the template, this saves so much time.)

**Comment by fwalch** [comment]
Glad you like it, thanks! :-)
